### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by hallgchris**

### CODE REVIEW

**Comment by hallgchris** [comment]
build 174

**Comment by hallgchris** [comment]
test

**Comment by hallgchris** [comment]
comment

**Comment by hallgchris** [comment]
comment

**Comment by hallgchris** [comment]
comment

**Comment by hallgchris** [comment]
build 81

**Comment by hallgchris** [comment]
build toolstests

**Comment by hallgchris** [comment]
build product

**Comment by milesizzo** [comment]
Building test server: https://working129.rome2rio.com

**Comment by hallgchris** [comment]
build toolstests

**Comment by hallgchris** [comment]
test test

**Pull request closed without merging**
